[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "wordpress"

[services.variables]
WP_SITE_TITLE      = "London Pentecostal Church"
WP_ADMIN_USER      = "lpcadmin"
WP_ADMIN_PASSWORD  = "Ch@ngeMe2026!"
WP_ADMIN_EMAIL     = "admin@londonpentecostalchurch.org"
WP_DEBUG           = "false"
MYSQL_HOST         = "mysql"
MYSQL_PORT         = "3306"
MYSQL_DATABASE     = "railway"
MYSQL_USER         = "railway"
MYSQL_PASSWORD     = "railway"
